### ISSUE TITLE
Add dependabot to project

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CASL#10]
**Description:**
Setup dependabot for the project by creating a dependabot YAML file.

**Use the YAML below:**
``` yaml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - "KinsonDigital/CASL"
    target-branch: "develop"
    labels:
      - "dependency update"

```

---

1. [ ] Dependabot operates and does what the hell its told.  :)
